.github/workflows/build.yml, .goreleaser.yaml, Dockerfile
Create a release step using goreleaser. It includes docker and homebrew build support, similar to what's done for pgroll.
=> Add release step to CI

README.md, pg2webhook.env
This PR updates the environment file for pg to webhooks to add the translator env variable, as well as update the readme config section accordingly (also formatting).
=> Update translator env variable

tools/webhook/webhook_server.go
This PR updates the dummy webhook server to pretty print the request body for demo purposes.
=> Pretty print request body in dummy webhook server

pkg/wal/processor/translator/wal_translator.go, pkg/wal/processor/translator/wal_translator_test.go
Update version finder to support using the LSN instead of a column.
=> Allow to define a version finder that uses LSN

pkg/transformers/builder/transformer_builder.go, pkg/transformers/greenmask/greenmask_integer_transformer.go, pkg/transformers/greenmask/greenmask_integer_transformer_test.go, pkg/transformers/transformer.go
This PR introduces `IntegerTransformer` which uses `greenmasktransformers.RandomInt64Transformer` under the hood.
=> Add gm integer transformer

pkg/transformers/builder/transformer_builder.go, pkg/transformers/greenmask/greenmask_choice_transformer.go, pkg/transformers/greenmask/greenmask_choice_transformer_test.go, pkg/transformers/transformer.go
Introduce `ChoiceTransformer` which uses greenmask's `RandomChoiceTransformer` under the hood.
=> Add choice gm transformer

pkg/transformers/builder/transformer_builder.go, pkg/transformers/greenmask/greenmask_unix_timestamp_transformer.go, pkg/transformers/greenmask/greenmask_unix_timestamp_transformer_test.go, pkg/transformers/transformer.go
Transform unix timestamps using greenmask's integer tranformer.
=> Add unix timestamp gm transformer

go.mod, go.sum, pkg/transformers/builder/transformer_builder.go, pkg/transformers/greenmask/greenmask_timestamp_transformer.go, pkg/transformers/greenmask/greenmask_timestamp_transformer_test.go, pkg/transformers/transformer.go
Introduce `UTCTimestampTransformer` which uses greenmask's Timestamp under the hood.
=> Add utc timestamp gm transformer

pkg/transformers/builder/transformer_builder.go, pkg/transformers/neosync/neosync_email_transformer.go, pkg/transformers/neosync/neosync_email_transformer_test.go, pkg/transformers/neosync/neosync_transformer.go, pkg/transformers/transformer.go
Add `EmailTransformer` which uses neosync's email transformer
=> Add ns email transformer

pkg/wal/processor/batch/wal_batch_sender.go
This PR updates the batch sender to not close the msg channel when there's a send error, since it will cause potential calls to `AddToBatch` from different go routines to panic when trying to send to a closed channel. 
The message channel should be closed by the caller using the `Close` function when it's done sending messages. If the send thread has stopped, an error will be returned when trying to add to the batch, preventing further processing.
Relates to #203
=> [Batch sender] Do not close msg channel on send error

internal/postgres/errors.go, pkg/wal/processor/postgres/postgres_batch_writer.go
=> Catch value too long error

.github/workflows/build.yml, Makefile, cli-definition.json, cmd/root_cmd.go, tools/build-cli-definition.go
Follows https://github.com/xataio/pgroll/pull/629 for `pgstream`. This would allow `pgstream` binary to be integrated in Xata CLI in a type safe manner.
=> feat(cli-definition): generate CLI definition as Json

pkg/transformers/builder/transformer_builder.go
=> Improve error message unsupported transformer config to include name

pkg/wal/processor/postgres/postgres_wal_ddl_adapter.go, pkg/wal/processor/postgres/postgres_wal_ddl_adapter_test.go
=> Fix syntax error with ddl adapter

cmd/config/config.go, cmd/config/config_env.go, docs/README.md, pkg/wal/replication/postgres/helper_test.go, pkg/wal/replication/postgres/pg_replication_handler.go, pkg/wal/replication/postgres/pg_replication_handler_test.go
This PR updates the errors for unmarshaling yaml configuration and no replication slot so that they're easier to understand. 
Closes #227
=> Improve errors

docs/README.md, pkg/transformers/builder/transformer_builder.go, pkg/transformers/neosync/neosync_lastname_transformer.go, pkg/transformers/neosync/neosync_lastname_transformer_test.go, pkg/transformers/transformer.go
Adding neosync's last name transformer.
=> Add neosync lastname transformer

docs/README.md, pkg/transformers/builder/transformer_builder.go, pkg/transformers/neosync/neosync_fullname_transformer.go, pkg/transformers/neosync/neosync_fullname_transformer_test.go, pkg/transformers/transformer.go
Adding fullname transformer from neosync
=> Add neosync fullname transformer

pkg/wal/processor/webhook/notifier/webhook_notifier.go
This PR stops closing the notify channel of the webhook notifier when there's a send error. It causes occasional errors during the tests due to `send on closed channel`. Example:
https://github.com/xataio/pgstream/actions/runs/14928897238/job/41939993372?pr=329
It was missed when fixing the batch sender (relates to https://github.com/xataio/pgstream/pull/212), since the webhook notifier doesn't use batches.
=> [Webhook Notifier] Do not close notify channel on send error

pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go, pkg/stream/stream.go, pkg/wal/processor/postgres/instrumented_wal_adapter.go, pkg/wal/processor/postgres/postgres_batch_writer.go
Add instrumentation to the wal adapter of the postgres batch writer.
Relates to #323
=> [Postgres Batch Writer] Add instrumentation

pkg/transformers/template_transformer.go, pkg/transformers/template_transformer_test.go
This PR adds support for greenmask's functions for templates.
https://github.com/eminano/greenmask/blob/main/pkg/toolkit/template_functions.go#L71-L199
=> Template transformer: Add greenmask toolkit functions

docs/README.md, pkg/transformers/template_transformer_test.go
This PR adds template transformer to the docs. Also a minor fix for the template test.
fixes: #234
=> Update docs to add template support

cmd/config/config_yaml.go
removing the empty check for transformers list
=> Allow empty transformer list config

docs/README.md, pkg/transformers/template_transformer.go
Adding the function map of the open source library sprig for template transformer
https://masterminds.github.io/sprig/
=> Add sprig template functions

cmd/config/config.go, pkg/transformers/neosync/neosync_transformer.go, pkg/wal/processor/transformer/wal_transformer.go
This PR fixes a panic on the neosync transformers when the transformation fails and the returned value is nil. 
The yaml config is also updated to support lowercase transformations.
=> Fix transformers panic

pkg/wal/processor/transformer/wal_postgres_transformer_parser.go, pkg/wal/processor/transformer/wal_postgres_transformer_parser_test.go
Adding the wildcard schema support for transformer validator.
=> Add schema wildcard supp for transformer validator

go.mod, go.sum
This PR updates the greenmask dependency.
Fixes #445
=> Update greenmask dependency

pkg/stream/stream_run.go
Fixes https://github.com/xataio/pgstream/issues/437#issuecomment-3083042519.
=> [Run] Do not access processor in error

docs/README.md, pkg/transformers/email_transformer.go
Follow up for https://github.com/xataio/pgstream/pull/517.
=> Update default replacement domain for email transformer 
