xataio/pgstream

- cmd/config.go
- go.mod
- go.sum
- pkg/schemalog/log_entry.go
- pkg/stream/config.go
- pkg/stream/stream_run.go
- pkg/wal/processor/search/opensearch/opensearch_adapter.go
- pkg/wal/processor/search/opensearch/opensearch_index_name.go
- pkg/wal/processor/search/opensearch/opensearch_store.go
- pkg/wal/processor/search/opensearch/opensearch_store_test.go
- pkg/wal/processor/search/search_store_retrier.go
- pkg/wal/processor/translator/wal_translator.go
- pkg/wal/processor/translator/wal_translator_test.go
This PR updates the hooks that allow to customise the use for the pgstream library:
- Add support to use a custom search index name adapter and a mapper
- Add granularity to filter wal data and schema events separately
Small improvements included:
- Update of pgx dependency 
- Removal of panic during log entry unmarshaling
- Apply search store retry logic by default (if no config is provided, there's a default that applies). If no retries are required, then the config must be explicitly updated accordingly.
The commits have been split for ease of reviewing.
> Update lib hooks

- cmd/config.go
- pkg/stream/config.go
- pkg/stream/integration/helper_test.go
- pkg/stream/integration/pg_kafka_integration_test.go
- pkg/stream/stream_run.go
- pkg/wal/checkpointer/kafka/wal_kafka_checkpointer.go
- pkg/wal/listener/kafka/wal_kafka_reader.go
This PR updates the kafka checkpointer and listener to use the same kafka reader. This will ensure the messages are fetched and committed by the same reader, which has shown to cause sporadic connection issues at startup when the reader connects to kafka, failing to receive any messages.
> Use the same kafka reader for fetching and committing messages

- pkg/kafka/instrumentation/instrumented_kafka_reader.go
- pkg/kafka/instrumentation/instrumented_kafka_writer.go
- pkg/kafka/kafka_reader.go
- pkg/otel/otel.go
- pkg/schemalog/instrumentation/instrumented_store.go
- pkg/stream/stream_run.go
- pkg/wal/processor/instrumentation/instrumented_wal_processor.go
- pkg/wal/processor/kafka/wal_kafka_batch_writer.go
- pkg/wal/processor/search/instrumentation/instrumented_search_store.go
- pkg/wal/processor/translator/wal_translator.go
- pkg/wal/replication/instrumentation/instrumented_replication_handler.go
This PR improves the instrumentation support of pgstream, by adding support for traces and extending the instrumentation coverage. Tracing/metrics are readily available with the library use for now. Out of the box instrumentation for the pgstream CLI tool will be integrated later on.
Commits have been split for ease of reviewing.
> Improve instrumentation

- pkg/wal/processor/kafka/wal_kafka_batch_writer.go
- pkg/wal/processor/search/search_store_retrier.go
- pkg/wal/processor/search/search_store_retrier_test.go
This PR updates the wal kafka batch writer to apply the constructor options after the internal writer is initialised (this allows us to wrap it with instrumentation). 
The search store retrier is updated to return dropped documents as failed documents in the `SendDocuments` method, instead of only returning retriable failed documents. This way the metric to track failed document errors accurately represents the results.
> Fix instrumentation

- .pre-commit-config.yaml
- Makefile
- pkg/log/logger.go
- pkg/wal/checkpointer/kafka/wal_kafka_checkpointer.go
- pkg/wal/listener/kafka/wal_kafka_reader.go
- pkg/wal/listener/postgres/wal_pg_listener.go
- pkg/wal/processor/kafka/wal_kafka_batch_writer.go
- pkg/wal/processor/search/search_batch_indexer.go
- pkg/wal/processor/translator/wal_translator.go
- pkg/wal/processor/webhook/notifier/webhook_notifier.go
- pkg/wal/processor/webhook/subscription/server/subscription_server.go
- pkg/wal/processor/webhook/subscription/store/cache/subscription_store_cache.go
- pkg/wal/processor/webhook/subscription/store/postgres/pg_subscription_store.go
- pkg/wal/replication/postgres/pg_replication_handler.go
This PR updates the logger library to use the field `module` instead of `service`, since `service` is commonly used by many logging platforms and it will overwrite the values. `module` aligns more with the concept for which it's currently used, since it's set per block of work.
The golangci-lint version is updated.
> Update logger field

- internal/postgres/errors.go
- internal/postgres/mocks/mock_pg_querier.go
- internal/postgres/pg_conn.go
- internal/postgres/pg_conn_pool.go
- internal/postgres/pg_querier.go
- internal/postgres/pg_tx.go
This PR adds support for executing operations within a transaction using the internal postgres library. It also adds error mapping to the querier implementations.
> Add tx support to postgres lib

- pkg/wal/processor/search/search_batch_indexer.go
Do not treat as data loss when a schema change is applied and the context is canceled. Return the error, and stop the search batch indexer instead to prevent data loss (the event won't be checkpointed and will be retried on the next service start). This is how data write and truncate events are handled currently, it was an oversight for schema changes.
> Return error when applying schema if context is canceled

- internal/postgres/mocks/mock_pg_querier.go
- internal/postgres/mocks/mock_rows.go
- pkg/schemalog/postgres/pg_schemalog_store_test.go
- pkg/snapshot/snapshot.go
- pkg/snapshot/store/mocks/mock_snapshot_store.go
- pkg/snapshot/store/postgres/pg_snapshot_store.go
- pkg/snapshot/store/postgres/pg_snapshot_store_test.go
- pkg/snapshot/store/snapshot_store.go
This PR adds a snapshot store to persist snapshot requests. This will be used by a snapshot server which will receive the requests, in order to have a persisted list of snapshots and their status.
Part of https://github.com/xataio/pgstream/issues/80
> Add snapshot store

- internal/json/json.go
- internal/searchstore/search_client.go
- pkg/schemalog/log_entry.go
- pkg/schemalog/schema.go
- pkg/wal/listener/kafka/wal_kafka_reader.go
- pkg/wal/listener/postgres/wal_pg_listener.go
- pkg/wal/processor/kafka/wal_kafka_batch_writer.go
- pkg/wal/processor/search/search_adapter.go
- pkg/wal/processor/search/search_store_retrier.go
- pkg/wal/processor/search/search_store_retrier_test.go
- pkg/wal/processor/search/store/search_adapter.go
- pkg/wal/processor/search/store/search_pg_mapper.go
- pkg/wal/processor/search/store/search_store.go
- pkg/wal/processor/translator/wal_translator.go
- pkg/wal/processor/webhook/notifier/webhook_notifier.go
This PR wraps the external json lib implementation under an internal package so that it can be easily replaced in all places where it's used. It updates processor side modules to benefit from the performance improvements of the library change.
It also updates the `GetTableByName` method to reduce unnecessary memory allocations.
Follow up on https://github.com/xataio/pgstream/pull/84.
> Wrap external json lib 

- pkg/wal/processor/kafka/wal_kafka_batch_writer.go
Currently there's a guard in place to make sure there are no messages sent to kafka that go over the limit in size. However, the check is only accounting for the serialised bytes of the value in the message, but not for the rest of the message (headers, metadata...). This PR updates the size check to ensure we leave some buffer to account for those extra parts of the message, discarding the message and logging it as data loss if the value is more than 95% of the limit.
An error log is added to identify when the send thread stops unexpectedly due to kafka errors.
> Reinforce kafka msg size guards

- internal/postgres/pg_replication_conn.go
- internal/postgres/pg_test.go
> Replace period on replication slot name

- .gitignore
- pkg/wal/processor/kafka/wal_kafka_batch_writer.go
- pkg/wal/processor/kafka/wal_kafka_batch_writer_test.go
- pkg/wal/processor/search/search_batch_indexer.go
- pkg/wal/processor/search/search_batch_indexer_test.go
- pkg/wal/processor/webhook/notifier/webhook_notifier.go
- pkg/wal/processor/webhook/notifier/webhook_notifier_test.go
Currently the processor implementations can deadlock under heavy load, if the batch send error channel doesn't get a chance to notify before the send go routine tries to send messages into the batch channel. This causes a situation where the send error channel is not checked because the for select is blocked trying to write, but the send error causes the reader of the unbuffered channel to stop, which makes it block on writes. 
Additionally, when the send go routine ends due to an error, the process will block when trying to enqueue the messages to be sent, since there are no readers for the channel.
In order to solve the first problem, the batch drain is done adding a check for the send errors. The second problem is fixed by adding a done channel to communicate to the processing when the …
> Fix deadlock under load

- pkg/snapshot/errors.go
- pkg/snapshot/snapshot.go
- pkg/snapshot/store/mocks/mock_snapshot_store.go
- pkg/snapshot/store/postgres/pg_snapshot_store.go
- pkg/snapshot/store/postgres/pg_snapshot_store_test.go
- pkg/snapshot/store/snapshot_store.go
This PR updates the existing snapshot store, since it was initially designed to work with the backfilling approach which required identity columns. Since we will no longer rely on a primary key/unique column to produce the snapshot, it can be removed. Additionally, the snapshot structs have been refined, separating the snapshot request, and including a more thorough recording of snapshot errors at snapshot/table level, which will be helpful to retry failed snapshots for only the affected relations. 
A new method to retrieve snapshot requests by schema is added.
> Update snapshot store

- internal/postgres/mocks/mock_pg_querier.go
- internal/postgres/mocks/mock_row.go
- internal/postgres/mocks/mock_tx.go
- internal/postgres/pg_conn.go
- internal/postgres/pg_conn_pool.go
- internal/postgres/pg_mapper.go
- internal/postgres/pg_querier.go
- internal/postgres/pg_tx.go
This PR updates the internal postgres library to support executing within a transaction providing transaction options. This will be required by the snapshoting implementation, since we'll need to set the options to repeatable read/read only.
> Update internal pg lib

- pkg/snapshot/generator/postgres/config.go
- pkg/snapshot/generator/postgres/helper_test.go
- pkg/snapshot/generator/postgres/pg_snapshot_generator.go
- pkg/snapshot/generator/postgres/pg_snapshot_generator_integration_test.go
- pkg/snapshot/generator/postgres/pg_snapshot_generator_test.go
- pkg/snapshot/generator/snapshot_generator.go
- pkg/snapshot/snapshot.go
This PR adds the logic to generate snapshots. It includes the interface and the postgres implementation. 
The postgres implementation relies on transaction snapshot ids which offer a consistent view of the database to read from, allowing to parallelise the work to snapshot schema tables by splitting the table pages into ranges based on the [ctid](https://www.postgresql.org/docs/current/ddl-system-columns.html#DDL-SYSTEM-COLUMNS-CTID) system column.
The snapshot generator concurrency can be configured, and the produced table rows can be processed by a configurable processor.
Integration and unit tests added.
Relates to #96
> Add snapshot generator

- pkg/wal/replication/instrumentation/instrumented_replication_handler.go
- pkg/wal/replication/mocks/mock_replication_handler.go
- pkg/wal/replication/postgres/pg_replication_handler.go
- pkg/wal/replication/postgres/pg_replication_handler_test.go
- pkg/wal/replication/replication_handler.go
This PR updates the replication handler to support retrieving the current LSN as well as starting replication from a provided LSN. This will be used by the snapshoting behaviour, to ensure we can retrieve the LSN before getting the transaction snapshot, so that when we finish the snapshot we can resume/start replication from the last processed event.
> Add support to provide LSN

- pkg/snapshot/errors.go
- pkg/snapshot/generator/helper_test.go
- pkg/snapshot/generator/snapshot_generator_recorder.go
- pkg/snapshot/generator/snapshot_generator_recorder_test.go
- pkg/snapshot/snapshot.go
- pkg/snapshot/store/mocks/mock_snapshot_store.go
- pkg/snapshot/store/postgres/pg_snapshot_store.go
- pkg/snapshot/store/postgres/pg_snapshot_store_test.go
This PR adds a decorator around a snapshot generator to record the request activity. It checks if there are any existing completed snapshots for the snapshot request, and parses the result to make sure if there are existing snapshots that completed with errors, only the failed tables are retried. 
It helps keep track of when a snapshot was requested and completed, and any potential errors during the processing. This will prevent the configured initial snapshot to be re-run every time pgstream is started.
> Add snapshot generator recorder

- pkg/snapshot/generator/snapshot_generator_aggregator.go
- pkg/snapshot/generator/snapshot_generator_aggregator_test.go
This PR adds a snapshot generator aggregator. This will allow us to combine both schema and data snapshotting when configured, as well as allowing other snapshot generator implementations to be added on later on.
> Add snapshot aggregator

- pkg/snapshot/generator/data/postgres/pg_schema_table_parser.go
- pkg/snapshot/generator/data/postgres/pg_schema_table_parser_test.go
- pkg/snapshot/generator/data/postgres/pg_snapshot_generator.go
- pkg/snapshot/generator/data/postgres/pg_snapshot_generator_test.go
This PR adds a table parser to the postgres snapshot generator. This allows to translate the wildcard table into the tables associated to the request schema without having to provide all of them explicitly.
> Add table parser in snapshot generator

- pkg/wal/processor/kafka/wal_kafka_batch_writer.go
- pkg/wal/processor/search/search_batch_indexer.go
- pkg/wal/processor/search/search_msg_batch.go
- pkg/wal/processor/webhook/notifier/webhook_notifier.go
This PR fixes a bug in the WAL processors where the send/notify channels are closed when the enqueuing fails for any reason, but it should only be closed when the send/notify thread stops (this signals the processor has stopped).
This can cause issues if the error returned by the `ProcessWALEvent` method is not treated as fatal, and the processor is called after an error, attempting to send a message on a closed channel with a send/notify thread still running.
Preventative nil checks added for the search indexer message.
> Fix processing bug

- pkg/wal/processor/search/search_adapter.go
- pkg/wal/processor/search/search_adapter_test.go
Support int32 as id column for seach
> Support int32 as id column

- internal/searchstore/elasticsearch/elasticsearch_client.go
- internal/searchstore/opensearch/opensearch_client.go
- internal/searchstore/search_errors.go
- pkg/wal/processor/search/errors.go
- pkg/wal/processor/search/search_batch_indexer.go
- pkg/wal/processor/search/search_batch_indexer_test.go
- pkg/wal/processor/search/store/search_store.go
When the `SendBulkRequest` opensearch/elasticsearch client returns an error, it's not being parsed like the rest of the client methods, which ends up treating all error status as critical. 
This PR updates the handling, so that validation query errors don't stop the processing of the search batch indexer.
> Fix validation error parsing on opensearch

- internal/postgres/pg_dump.go
- internal/postgres/pg_dump_pg_restore_integration_test.go
- internal/postgres/pg_restore.go
- internal/testcontainers/test_elasticsearch_container.go
- internal/testcontainers/test_kafka_container.go
- internal/testcontainers/test_opensearch_container.go
- internal/testcontainers/test_postgres_container.go
- pkg/stream/integration/setup_test.go
This PR adds the `pg_dump`/`pg_restore` functionalities to the internal postgres library. A testcontainers package is created in order to reuse the setup for integration tests.
> Add pg_dump/pg_restore to internal library

- pkg/snapshot/errors.go
- pkg/snapshot/errors_test.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator.go
- pkg/snapshot/generator/snapshot_generator_recorder.go
- pkg/snapshot/generator/snapshot_generator_recorder_test.go
- pkg/snapshot/store/postgres/pg_snapshot_store_test.go
The snapshot errors are used to be able to record the snapshot status in the snapshot requests store, to keep track of issues during snapshotting. This PR updates the snapshot level errors as strings instead of errors, so that they are properly stored, similarly to what's done for the table errors.
Tests for errors are added.
> Treat snapshot errors as strings for recording

- pkg/snapshot/generator/postgres/data/pg_snapshot_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator_test.go
This PR adds an implementation of the snapshot generator that generates a postgres schema snapshot using `pg_dump` and `pg_restore` postgres utilities.
> Add pg_dump/pg_restore schema snapshot generator

- pkg/transformers/builder/transformer_builder.go
- pkg/transformers/greenmask/greenmask_float_transformer.go
- pkg/transformers/greenmask/greenmask_float_transformer_test.go
- pkg/transformers/transformer.go
Introduce `FloatTransformer` which uses `greenmasktransformers.RandomFloat64Transformer` under the hood.
> Add gm float transformer

- Makefile
- go.sum
- internal/postgres/errors.go
- pkg/wal/processor/postgres/postgres_batch_writer.go
- pkg/wal/processor/postgres/postgres_batch_writer_test.go
This PR updates the query flushing behaviour of the postgres batch writer to ensure that if one of the queries within a batch fails with a non internal error (constraint violation, relation doesn't exist), the error is logged as dataloss, and the rest of the queries are retried and checkpointed, instead of stopping the processor at the first query error.
This aligns with the behaviour of all the other processors.
> [PostgreSQL processor] Handle errors gracefully

- pkg/transformers/greenmask/greenmask_integer_transformer.go
- pkg/transformers/greenmask/greenmask_integer_transformer_test.go
- pkg/transformers/greenmask/greenmask_unix_timestamp_transformer.go
- pkg/transformers/greenmask/greenmask_unix_timestamp_transformer_test.go
- pkg/transformers/greenmask/greenmask_uuid_transformer.go
Use int instead of int64 as it's not supported in yaml format.
This will cause us to accept 4 byte integers for integer transformers. We should find a way to support int64.
For unix transformers, the input type will be string, which will be parsed into int64 internally.
> Do not use int64 as yaml parameters

- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
This PR updates the pgdump/pgrestore snapshot generator so that it doesn't try to create the `public` schema, which would trigger an error since `public` schema is created by default in PostgreSQL databases.
Closes #188
> [Snapshots] Do not create public schema

- pkg/wal/processor/postgres/postgres_batch_writer.go
Add a debug log when sending batch of queries and do not log as error `context.Canceled`.
> [Postgres Processor] Improve batch writer logs

- pkg/snapshot/generator/postgres/data/pg_snapshot_generator.go
- pkg/wal/listener/snapshot/adapter/wal_snapshot_generator_adapter.go
- pkg/wal/processor/postgres/postgres_batch_writer.go
This PR updates the postgres data snapshot generator to remove the nested transactions during the table range processing, which makes the process slower and sometimes even stuck. This was not necessary, but an oversight during implementation.
> [Snapshots] Fix data snapshot concurrency

- internal/postgres/pg_utils.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator_test.go
- pkg/snapshot/store/postgres/pg_snapshot_store.go
- pkg/wal/listener/snapshot/builder/wal_listener_snapshot_generator_builder.go
- pkg/wal/processor/postgres/postgres_wal_dml_adapter.go
This PR adds a few small bug fixes:
- Add quote identifiers to snapshot schema/tables
- Do not translate wildcard `*` tables for pgdump schema snapshots, since it prevents all resources in a given schema to be dumped by having a list of tables.
> [Snapshot] `pg_dump` snapshot fixes

- cmd/config/config.go
This PR resets the config file after merging the transformation rules yaml file from the env file. Otherwise, we can't determine if it's the yaml or env config, to parse it into the stream config for the run.
> Reset config file after reading transformation file

- cmd/config/config.go
- cmd/config/config_env.go
- go.mod
This PR changes the library used to unmarshal yaml files, from viper to yaml, to allow reading case sensitive keys correctly.
fixes: #277
> Read config case sensitive, using yaml unmarshal

- pkg/wal/processor/filter/wal_filter.go
- pkg/wal/processor/filter/wal_filter_test.go
- pkg/wal/processor/mocks/mock_processor.go
This PR fixes an edge case with the filtering lists, where if both schema qualified tables and wildcard ones are present, only the schema qualified are matched, skipping events that should otherwise be processed.
> Merge wildcard tables in filter

- internal/postgres/pg_dump.go
- internal/postgres/pg_dump_pg_restore_integration_test.go
- internal/postgres/pg_restore.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator_test.go
This PR updates the pgdump/pgrestore schema snapshot generator with the following changes:
- The snapshot tables are not passed as pg_dump filter, but instead excluded_tables are retrieved for the snapshot schema and used, so that any non table object is dumped along with the selected tables.
- The pg_dump command now uses plain text format and the clean option instead of using `pg_restore` with clean, since the command fails when trying to delete the public schema. With `psql` we can parse the output and ignore the error, since the rest of types are recreated appropriately.
These two changes should improve the experience of repeatable snapshots for postgres to postgres.
> [Snapshots] Fix repeatable snapshots

- pkg/stream/stream_run.go
- pkg/wal/processor/transformer/wal_transformer_validator.go
- pkg/wal/processor/transformer/wal_transformer_validator_test.go
This PR updates the transformer validator to use a connection pool instead of reusing the same connection for the different schema table queries. This should prevent `conn busy` errors during the validation.
> Use connection pool in transformer validator

- pkg/wal/processor/transformer/wal_transformer_validator.go
- pkg/wal/processor/transformer/wal_transformer_validator_test.go
This PR closes the rows immediately to release the underlying connection and prevent potential `conn busy` errors when the pool is maxed out. The current implementation uses a defer that will only close once the for loop is done, holding as many connections open as tables in the range.
Documentation: https://pkg.go.dev/github.com/jackc/pgx/v5#Rows
>Rows must be closed before the *Conn can be used again.
Relates to #293.
> Close rows immediately to release connection

- cmd/config/config_env.go
- cmd/config/config_yaml.go
- cmd/config/test/test_config.yaml
- cmd/config/test/test_transformer_rules.yaml
- pkg/stream/integration/helper_test.go
- pkg/stream/stream_run.go
- pkg/wal/processor/transformer/wal_transformer.go
- pkg/wal/processor/transformer/wal_transformer_rules.go
- pkg/wal/processor/transformer/wal_transformer_test.go
- pkg/wal/processor/transformer/wal_transformer_validator.go
- pkg/wal/processor/transformer/wal_transformer_validator_test.go
Single PR for both adding noop transformer support and strict validation mode.
Parsing the config, if no validation mode is not provided, the default will be `relaxed` mode. If validation mode is set to `strict` we'll be validating that all columns for that particular table are present in the transformer config, by comparing them to the column list we get from postgres.
fixes: #259 
fixes: #260
> Add noop transformers support and Strict validation mode

- pkg/transformers/greenmask/greenmask_uuid_transformer.go
- pkg/transformers/greenmask/greenmask_uuid_transformer_test.go
Do not parse string into uuid, for uuid transformer, but directly use the bytes instead.
> UUID Transformer: Do not parse string into uuid

- Makefile
This PR adds a make build target that populates the cmd version, so that the binary version used locally can be verified for debugging purposes.
Fixes #308
> Add make build with version

- pkg/transformers/builder/transformer_builder.go
- pkg/transformers/literal_string_transformer.go
- pkg/transformers/literal_string_transformer_test.go
- pkg/transformers/transformer.go
- pkg/wal/processor/transformer/wal_transformer_validator.go
Adding `LiteralStringTransformer` which transforms anything into given string. This is expected to be used as an escape hatch, mostly for non supported types.
fixes: #311
> Add literal string transformer

- docs/README.md
Adding literal string transformers to docs, into the newly created section `Other Transformers`. I think we can add other transformers that we implemented ourselves to that section as well, such as phone number transformer.
> Update docs for literal string transformer

- pkg/transformers/builder/transformer_builder.go
- pkg/transformers/template_transformer.go
- pkg/transformers/template_transformer_test.go
- pkg/transformers/transformer.go
This PR adds template transformer which gets a template during creation, then executes it when transforming data. This transformer also supports dynamic values using other column values.
Other than the functionalities supported by default by templates, this PR introduces two methods, namely `GetValue` and `GetDynamicValue`, allowing users to build up more complex templates using all the column values in a row.
Considering adding support for wide range of helper functions supported [here](https://github.com/eminano/greenmask/blob/main/pkg/toolkit/template_functions.go#L71-L199) in greenmask, in a followup PR.
Skipping updating the docs for now, will do it once we're done with templates.
> Add template transformer

- .golangci.yml
- cli-definition.json
- cmd/root_cmd.go
- cmd/run_cmd.go
- cmd/snapshot_cmd.go
- internal/profiling/profiling.go
This PR adds basic support for profiling for run/snapshot CLI commands. A flag `--profile` is added, which will create cpu and memory profile files if enabled, as well as start an http server exposing a `/debug/pprof` endpoint. The files will only be created on `snapshot` mode, since run is a long running process.
For now the values for the filenames and the server address are hardcoded to `mem.prof`, `cpu.prof` and `localhost:6060`.
> Add basic profiling support to CLI

- docs/README.md
- pkg/transformers/builder/transformer_builder.go
- pkg/transformers/phone_number_transformer.go
- pkg/transformers/phone_number_transformer_test.go
This PR adds `prefix` as a dynamic parameter for phone number transformer.
Also updating the docs for dynamic parameters.
fixes: #344
> Phone number dynamic country code

- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator_test.go
This PR fixes an edge case when dumping sequence data to only call `pg_dump` if there are sequences created by the schema dump. Currently when there are no sequences the table filter is not used, and all data is dumped.
> [Snapshot] Do not dump sequence values if there's no sequences

- docs/README.md
- pkg/stream/integration/helper_test.go
- pkg/stream/integration/pg_pg_integration_test.go
- pkg/stream/integration/snapshot_pg_integration_test.go
- pkg/wal/processor/postgres/postgres_bulk_ingest_writer.go
- pkg/wal/processor/postgres/postgres_bulk_ingest_writer_test.go
This PR updates the postgres bulk ingest writer logic to prevent copying generated columns (excluding identities). Generated columns are computed when written, and cannot be written to directly. The COPY command does not support them. 
https://www.postgresql.org/docs/current/ddl-generated-columns.htm 
Instead of modifying the snapshotting process to remove the generated columns from the snapshot, the changes are done on the postgres target side, since the snapshot can be used with any supported target, and this is only an issue for the postgres usecase. For any other target, we'll need to have the generated columns along with the rest, since they won't have the postgres logic embedded to generate it.
Fixes #373
> [Snapshot] Do not copy generated columns

- cmd/snapshot_cmd.go
- docs/README.md
This PR disables the creation of the target database by default on the snapshot command. If the database needs to be created, it will have to be configured via the env/yaml configuration explicitly, since this is a relatively invasive operation, and it will fail if the database is in use or the recorder is configured to use the same database.
> [Snapshot] Disable target database creation by default

- cmd/config/config.go
- cmd/config/config_env.go
- cmd/config/config_yaml.go
- docs/README.md
This PR updates the defaults for the postgres writer batching when bulk ingest is enabled, since the batch size/bytes/timeout need to be adjusted to improve the performance of the `COPY`, which works best with large sets of data.
> [Postgres Writer] Update batch defaults when bulk enabled

- docs/README.md
- pkg/transformers/builder/transformer_builder.go
- pkg/transformers/json_transformer.go
- pkg/transformers/json_transformer_operation.go
- pkg/transformers/json_transformer_test.go
- pkg/transformers/template_transformer_test.go
- pkg/transformers/transformer.go
- transformers-definition.json
Adding JSON transformer for json and jsonb date types of postgres. This transformer executes a list of given operations on the json data to be transformed.
All operations must be either `set` or `delete`. 
`set` operations support literal values as well as templates, making use of `sprig` and `greenmask`'s function sets. Also, like the template transformer, `.GetValue` and `.GetDynamicValue` functions are added. Unlike template transformer, here `.GetValue` refers to the value at given path, rather than the entire JSON object; whereas `.GetDynamicValue` is again used for referring to other columns.
`delete` operations simply delete the object at the given path.
`Transform` errors out if the given path does not exists and the parameter `error_not_exist` - which is false by default - is set …
> Json transformer support

- pkg/snapshot/generator/mocks/mocks_row_processor.go
- pkg/snapshot/generator/postgres/data/helper_test.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator_integration_test.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator_test.go
- pkg/snapshot/snapshot.go
- pkg/stream/stream_run.go
- pkg/stream/stream_snapshot.go
- pkg/wal/listener/snapshot/adapter/wal_process_event_adapter.go
- pkg/wal/listener/snapshot/builder/wal_listener_snapshot_generator_builder.go
- pkg/wal/listener/wal_listener.go
- pkg/wal/processor/batch/wal_batch_sender.go
- pkg/wal/processor/batch/wal_batch_sender_test.go
This PR updates the postgres data snapshot generator to make sure the rows processor has finished before calling the next snapshot step. Otherwise, we can encounter situations where the index/constraint creation starts before all the data has been fully snapshoted, potentially leading to constraint issues since the data is not valid yet.
By closing the processor after the snapshot is done we guarantee that we wait for all the in-flight batches to complete before continuing.
> [Snapshot] Wait for all tables to finish processing data

- pkg/transformers/neosync/errors.go
- pkg/transformers/neosync/neosync_firstname_transformer.go
- pkg/transformers/neosync/neosync_firstname_transformer_test.go
- pkg/transformers/neosync/neosync_lastname_transformer.go
- pkg/transformers/neosync/neosync_lastname_transformer_test.go
- pkg/transformers/neosync/neosync_transformer.go
This PR adds the error catching mechanism for neosync transformers. As the first error to be catch, this PR catches `unable to find candidates with range` errors that are thrown by first name or last name transformers when trying to generate a name with single character. In that case we ignore the error and return a random letter as the new value.
Adding checks for `max_length` > 0 or not.
Also appending `neosync transformer:` to the beginning of all error messages that come from neosync `Transform` func.
fixes: #393
> Fix single letter first/last name neosync transformer

- cmd/config/config_env.go
- cmd/config/config_yaml.go
- cmd/config/helper_test.go
- pkg/snapshot/errors.go
- pkg/snapshot/errors_test.go
- pkg/snapshot/generator/instrumentation/instrumented_snapshot_generator.go
- pkg/snapshot/generator/postgres/data/config.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator_integration_test.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator_test.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator_test.go
- pkg/snapshot/generator/postgres/schema/schemalog/snapshot_schemalog_generator.go
- pkg/snapshot/generator/postgres/schema/schemalog/snapshot_schemalog_generator_test.go
- pkg/snapshot/generator/postgres/tablefinder/pg_snapshot_table_finder.go
- pkg/snapshot/generator/postgres/tablefinder/pg_snapshot_table_finder_test.go
- pkg/snapshot/generator/snapshot_generator_recorder.go
- pkg/snapshot/generator/snapshot_generator_recorder_test.go
- pkg/snapshot/snapshot.go
- pkg/snapshot/store/instrumentation/instrumented_snapshot_store.go
- pkg/snapshot/store/postgres/pg_snapshot_store.go
- pkg/snapshot/store/postgres/pg_snapshot_store_test.go
- pkg/wal/listener/snapshot/adapter/config.go
- pkg/wal/listener/snapshot/adapter/wal_snapshot_generator_adapter.go
- pkg/wal/listener/snapshot/adapter/wal_snapshot_generator_adapter_test.go
This PR updates the snapshot interface to support providing multiple schemas per snapshot. This will allow to perform the pg_dump of different schemas together to prevent missing dependencies, since it currently performs separate dumps that will fail if they are dependent on each other. 
This fixes https://github.com/xataio/xata-actions-demo/actions/runs/15486471181/job/43602182511.
The main changes are the switch from handling a single schema/tables to handling multiple. Most of the logic remains the same. Main changes:
- The wal snapshot adapter logic is moved to the data snapshot generator, since it's the one that will now parallelise the schema processing
- The pgdump/pgrestore schema snapshot generator is updated to provide the options for all schemas and their tables
- The snapshot …
> [Snapshot] Support multi-schema snapshots

- go.mod
- go.sum
- internal/postgres/pg_restore.go
- internal/progress/mocks/mock_progress_bar.go
- internal/progress/progress_bar.go
- pkg/snapshot/generator/postgres/data/instrumented_table_snapshot_generator.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator.go
- pkg/snapshot/generator/postgres/data/pg_snapshot_generator_test.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
- pkg/wal/listener/snapshot/builder/wal_listener_snapshot_generator_builder.go
This PR adds progress tracking to the data snapshots. The initial idea was to have a progress bar for each table being snapshotted. However, libraries supporting multiple progress bars ([multibar](https://github.com/sethgrid/multibar), [mpb](https://github.com/vbauerster/mpb) and [uiprogress](https://github.com/gosuri/uiprogress)) didn't show the progress properly, duplicating the result rather than updating the existing bar. 
Instead, this PR reports the progress for all tables in a schema in the same progress bar, using the [progressbar](https://github.com/schollz/progressbar) library.
The progress uses the total bytes for the snapshotted tables (using `pg_table_size` to avoid including indices which are snapshotted separately), and the average row bytes to calculate the progress made …
> [Snapshot] Data progress tracking

- pkg/wal/processor/postgres/postgres_wal_dml_adapter.go
- pkg/wal/processor/postgres/postgres_wal_dml_adapter_test.go
When building UPDATE queries, arg count in the WHERE clause must start from the arg count used in the SET clause. We currently start it from the total column count, resulting error when there's a generated column that is skipped in the SET clause.
Also adding a test for generating update query with a generated column.
> Fix placeholderOffset for update queries

- pkg/snapshot/generator/postgres/schema/schemalog/snapshot_schemalog_generator.go
- pkg/wal/listener/snapshot/builder/wal_listener_snapshot_generator_builder.go
- pkg/wal/processor/postgres/postgres_wal_ddl_adapter.go
- pkg/wal/processor/postgres/postgres_wal_ddl_adapter_test.go
Currently any non `public` schemas are not replicated to postgres, since the `CREATE SCHEMA` query is not executed. This affects both the schema snapshot in `schemalog` mode and the replication to postgres.
This PR updates the DDL adapter to create the schema if it doesn't exist when receiving a DDL event. It also fixes the condition to not add `DEFAULT` statements in table creation to generated columns.
> [Postgres Writer] Create schema if not exists

- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator_test.go
- pkg/wal/listener/snapshot/builder/wal_listener_snapshot_generator_builder.go
This PR updates the pgdump/restore snapshot generator to not receive the exploded schema/tables values obtained by the schema/table discovery step, but rather the ones originally requested by the user, since the wildcard values both for tables and schemas, affect the options passed to the `pg_dump` command. 
If we receive all the explicit schemas/tables on input, we'll apply filters that are not necessary and will in some cases produce different outputs than the expected ones. By having the wildcard component, we can optimise and simplify the pg_dump options.
Fixes https://github.com/xataio/xata-actions-demo/actions/runs/15829106209/job/44616940684.
> [Snapshot] Fix pg_dump multi schema support

- cmd/run_cmd.go
- pg2pg.yaml
- pkg/stream/stream.go
- pkg/stream/stream_run.go
- pkg/stream/stream_snapshot.go
This PR updates the stream processor constructor to factor in if the postgres processor is for replication or snapshots, and only applies the bulk ingest configuration for the snapshots. 
The bulk ingest is enabled by default when `snapshot_and_replication` mode is enabled, while keeping the normal batch writer for replication traffic, required for keeping up with all types of workloads and DDL changes while preserving the order.
Without these changes either the bulk load was applied to both snapshot and replication traffic, or to none. Given the constraints of the replication traffic, it forced initial snapshots to be performed using the basic postgres writer instead of the bulk one, which is much faster and efficient for larger databases.
Closes #434
> [Postgres] Support bulk initial snapshots in replication

- pkg/wal/processor/search/search_adapter.go
- pkg/wal/processor/search/search_adapter_test.go
- pkg/wal/processor/search/store/search_pg_mapper.go
- pkg/wal/processor/search/store/search_pg_mapper_test.go
This PR updates the search mapping to handle UUID types properly, by making them supported identity types and parsing values to use the string representation.
Fixes #433
> [Search Processor] Handle uuid type for search mapping

- internal/log/zerolog/zerolog.go
- internal/searchstore/search_client.go
- pkg/wal/processor/kafka/wal_kafka_batch_writer.go
- pkg/wal/processor/postgres/postgres_batch_writer.go
- pkg/wal/processor/postgres/postgres_bulk_ingest_writer.go
fix inconsistent struct name in comment
> chore: fix inconsistent struct name in comment

- Makefile
- cmd/config/config_yaml.go
- cmd/config/config_yaml_fuzz_test.go
This PR fixes the issue where having the snapshot mode set to `full`/`data` would expect the `data` section of the yaml configuration to be present, or would crash otherwise. 
A check is added to make sure that if the data section is not provided, defaults will apply instead. 
Fuzzing has also been introduced, for local use for now, to identify crash paths for the yaml configuration parsing.
> Fix config data crash

- cli-definition.json
- cmd/root_cmd.go
- cmd/run_cmd.go
- internal/postgres/pg_utils.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator.go
- pkg/snapshot/generator/postgres/schema/pgdumprestore/snapshot_pg_dump_restore_generator_test.go
- pkg/snapshot/generator/postgres/tablefinder/pg_snapshot_table_finder.go
- pkg/snapshot/generator/postgres/tablefinder/pg_snapshot_table_finder_test.go
This PR updates the syncing of the schemalog table to properly handle wildcard schemas. Currently it was creating a "*" schema since it didn't explode it into the relevant ones. 
Since the schemalog table wasn't recording the right schemas, this was affecting DDL replication as well when using the `*.*` filter on snapshots.
Schema/table discovery utilities have been extracted into the postgres library, since they were used in multiple places. The `dump-file` flag has been added to the run command (already supported in the snapshot cmd), to allow for easier debugging when using the run command with initial snapshot enabled.
Fixes https://github.com/xataio/pgstream/issues/504
> Fix schemalog snapshot syncing for wildcard schemas

- README.md
- docs/cli.md
- docs/tutorials/postgres_to_opensearch.md
- docs/tutorials/postgres_to_postgres.md
- docs/tutorials/postgres_to_webhooks.md
- docs/tutorials/postgres_transformer.md
Simplify the usage section so that pgstream is easier to run and test, leveraging the new `--init` flag on the `run` command to simplify the setup. 
Preview: https://github.com/xataio/pgstream/tree/simplify-usage-in-readme
> [Docs] Simplify usage section
